apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: volunteer-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: volunteer-service

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
