apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-service
  namespace: solidarytech
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: donation-service
  template:
    metadata:
      labels:
        app: donation-service
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: donation-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION | quote }}

            - name: AWS_SQS_URL
              value: {{ .Values.env.AWS_SQS_URL | quote }}

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: solidarytech-database
                  key: database-url

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
