replicaCount: 1

image:
  repository: 212792011616.dkr.ecr.us-east-1.amazonaws.com/solidarytech-ngo-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

containerPort: 8081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5
