
apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: ngo-service

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP

